/**
 * SmashBoom — Anime-style pickup lines
 * Used by the SmashBoom feature to randomly flirt with group members.
 */
export const SMASHBOOM_LINES: string[] = [
    // ── Anime references ──────────────────────────────────────────────────────
    "Are you a shinigami? Because you just stole my heart... and probably my soul too. 💀❤️",
    "You don't need a Sharingan to see that I like you. 👁️",
    "My heart beats faster than All Might's punches whenever I see you. 💪❤️",
    "I don't need seven dragon balls — I already found my wish standing right here. 🐉",
    "Are you from Fairy Tail? Because you just cast a spell on my heart. ✨",
    "You're so cute that even Rem would switch loyalties. 🌸",
    "You must be a tsundere, because every time I look at you, my heart goes doki doki. 💕",
    "Are you an isekai protagonist? Because meeting you feels like the start of a fantasy. 🌟",
    "You're the Tohru to my Kobayashi — I didn't know I needed you until now. 🐉",
    "I've watched 500 anime and none of them prepared me for how beautiful you are. 🎭",
    "Are you from the Soul Society? Because you look absolutely heavenly. 👼✨",
    "My power level goes over 9000 every time you walk into the room. 💥",
    "Stop being so cute, you're making my power level rise uncontrollably. 🔥",
    "You make my heart go *ara ara*... 🍵",
    "Even in a parallel universe, I'd choose you every single time. 🌌",
    "You're rarer than an SSR card, and I'm the luckiest player alive. 🌟",
    "Are you a gacha pull? Because I'd spend every last gem for you. 💎",
    "In the game of love, you're the final boss I never want to defeat. ⚔️",
    "You're like a limited edition waifu card — absolutely priceless. 🃏",
    "Call me your servant, because I'd follow you to the ends of this world, Master. 🎀",
    "Are you a magic spell? Because I can't stop thinking about you no matter what I do. ✨",
    "My love for you is like an anime filler arc — it literally never ends. 😭💕",
    "Is your name Naruto? Because you just ran straight into my heart at full sprint. 🍥",
    "I'd give up my entire anime marathon for just one date with you. 🎌",
    "You're the main character energy in the story of my life. 📖✨",
    "Are you a healer? Because just one look from you cured all my loneliness. 💊❤️",
    "I looked up 'beautiful' in the dictionary and it just had your name. 📖",

    // ── Sweet & cheesy ────────────────────────────────────────────────────────
    "If you were a star, you'd be the brightest one in the galaxy. ⭐",
    "Excuse me, did you just smile at me? My heart just forgot how to beat. 😶‍🌫️💓",
    "I was going to play it cool, but honestly — you broke that plan the second I saw you. 🥺",
    "Are you a camera? Every time I look at you, I smile. 📸",
    "Do you believe in love at first ping? Because here we are. 💬❤️",
    "You must be WiFi, because I feel a strong connection. 📶💕",
    "Is your name Google? Because you have everything I've been searching for. 🔍",
    "If beauty were a crime, you'd be serving a life sentence. ⚖️😍",
    "You're the reason my notifications are always on. 🔔❤️",
    "I'd never skip your cutscene. Not even once. 🎮💕",
    "Are you a savepoint? Because I never want to lose this moment. 💾",
    "You must be a rare spawn, because I've been waiting for someone like you forever. 🌸",
    "Every love song makes sense now that I've met you. 🎶",
    "If I had a gold coin for every time I thought of you, I'd be richer than the whole economy system. 💰",
    "You're the plot twist I never saw coming but absolutely needed. 📚",
    "My whole storyline changed the moment you appeared. 🎬",
    "Are you a quest? Because I'd drop everything else just to complete you. 🗺️",
    "I don't need a wish list anymore — you're everything on it. 🌠",
    "You're not just a side character — you're my entire story. 📖💗",
    "I'd battle a thousand raid bosses just for a chance to be near you. 🛡️❤️",

    // ── Funny & playful ───────────────────────────────────────────────────────
    "Are you a loading screen? Because I'd wait for you forever. ⏳😅",
    "My Wi-Fi was weak but your smile gave me full bars. 📶😂",
    "You're like a good ending — rare, precious, and worth every second. 🏆",
    "I tried to think of a smooth pickup line, but honestly, you make me too nervous. 🫣💕",
    "Warning: talking to you may cause uncontrollable smiling. 😄⚠️",
    "Are you a bug in my code? Because I can't stop thinking about you no matter how hard I try. 🐛💻",
    "I may not be a genie, but I can make your wish to be noticed come true. 🧞",
    "My heart has better ping when you're around. 📡❤️",
    "You leveled up my happiness stat the moment you appeared. 📈😊",
    "If cuteness had a leaderboard, you'd be permanently #1. 🏅",
    "I was going to say something smart, then I saw you and forgot everything. 🧠💨",
    "Are you a critical hit? Because you just dealt max damage to my heart. ⚔️💔➡️❤️",
    "You're like the secret ending — not everyone finds it, but it's the best one. 🔑✨",
    "My character sheet says: Weakness — you. 📜",
    "Error 404: Words not found. Have you seen how cute you are?? 💻😭",

    // ── Desi + anime mix ─────────────────────────────────────────────────────
    "Bhai teri ek smile mein itna power hai ki mera health bar full ho jaata hai. 💚",
    "Tu toh ekdum SSR tier ka/ki hai — main toh sirf common hun tere saamne. 🃏",
    "Agar pyaar ek anime hota, tu definitely main character hota/hoti. 🌟",
    "Dekh bhai, mujhe duniya ki sab cheez mili hai lekin teri ek nazar nahi. 🥺",
    "Teri muskaan dekh ke lagta hai — yaar, ye real hai ya isekai? 🌸",
    "Tu itna/itni cute kyun hai? Mera cooldown period bhi khatam nahi hota teri soch ke. 😤❤️",
    "Tujhe dekh ke dil bolta hai: *checkpoint saved* 💾",
    "Agar tu quest hota, main kabhi complete nahi karta — bas khelta rehta. 🎮",
    "Yaar teri ek smile mujhe 5 star rating de deti hai life ko. ⭐⭐⭐⭐⭐",
    "Main toh bas ek normal player hun, tu clearly legendary loot hai. 🏆✨",

    // ── Extra sweet ───────────────────────────────────────────────────────────
    "If stars fell every time I thought of you, the sky would be empty by now. 🌌",
    "You're the type of person songs are written about. 🎵",
    "I didn't believe in love at first sight until I saw your username. 💬❤️",
    "You're the rare exception to every rule I've ever had. 💫",
    "Meeting you was the best random event this game ever generated. 🎲❤️",
    "You're not just pretty — you're the whole vibe. 🌸✨",
    "Every time you show up, the whole room's energy changes. ⚡",
    "I could talk to you forever and it still wouldn't feel like enough. 🗣️❤️",
    "You have this way of making ordinary moments feel like cutscenes worth watching. 🎬",
    "I think the universe has good taste — it put you in my world. 🌍💗",

    // ── High School DxD — Character Dialogues ─────────────────────────────────
    "Oppai wa saikou da! Teri ek nazar meri zindagi ka mission change kar deti hai! 🐉",
    "Main Rias Gremory hoon — aur jo bhi mujhe pasand hai, usse main kabhi akela nahi chhodti. ❤️",
    "*Ara ara~* Kya soch rahe ho tum? Bata do, main sun rahi hoon~ 🍵",
    "Sekiryuutei ka power sirf ladne ke liye nahi — apno ko bachane ke liye hai! 💪",
    "Jo bhi mere dil ko haath lagayega, use Power of Destruction ka swaad milega. 🔥",
    "*Fufufu~* Itna dar kyun rahe ho? Main tumhe kuch bura nahi karungi... zyada~ ⚡",
    "Main haar sakta hoon, lekin kabhi bhaagunga nahi — dil kabhi nahi jhukega! 🐉",
    "Occult Research Club mera dusra ghar hai — aur tum bhi isme aa sakte ho. ✨",
    "Sword Birth — jo bhi blade chahiye, wo bana sakta hoon. Tere liye bhi. ⚔️",
    "Main Nekoshou hoon — chhoti zaroor hoon, par mera punch bilkul chhota nahi hai. 🐱",
    "Twilight Healing — teri har chot theek kar dungi, chahe waqt lage jitna lage. 💊❤️",
    "Durandal ke saamne koi tikta nahi — par tere saamne main khud jhuk jaati hoon. ⚔️",
    "God ki kasam, main hamesha sach ka saath dungi — aur sach ye hai ki tu bahut cute hai! 🕊️",
    "Magic circles aur runes meri speciality hai — par tera dil decode karna zyada mushkil hai. 💫",
    "Main Valkyrie hoon, aur abhi bhi single — tere sath ye problem fix ho sakti hai. 🌸",
    "Discipline zaroori hai — par tere liye main ek baar rules toda sakti hoon. 📘",
    "Main sirf strongest se ladta hoon — aur tu clearly meri sabse badi weakness hai. 🌟",
    "Hakuryuukou hoon main — par teri ek smile mujhe White Dragon se insaan bana deti hai. 🤍",
    "Sacred Gears ki research mera kaam hai — par tujhse interesting kuch nahi mila abhi tak. 🔬",
    "...main sirf shaanti chahti hoon. Tere saath. 🌌",
    "Ek Rating Game ho ya zindagi ki ladai — main apne logon ko kabhi akela nahi chhodti. ❤️",
    "Ddraig, ek aur round — kyunki ye dil dekhne layak insaan hai! 🐉🔥",
    "Main aadhi fallen angel, aadhi devil — dono taraf ki best qualities tere liye hain~ 😈",
    "Issei-sama ke baad, tum ho jo mujhe seriously impress karte ho. 🍳✨",
    "Chahe Underworld ho ya human world — tera saath ho toh sab theek hai. 🌍",
]
